name: Haskell CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack
      - name: Build
        run: stack build --fast
      - name: Run tests
        run: stack test --fast

