name: Test

on: [push]

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ matrix.os }}-stack
      - if:  matrix.os  == 'macos-latest'
        run: brew install haskell-stack
      - name: Build
        run: stack build --fast
      - name: Run tests
        run: stack test --fast

