name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - if: matrix.os  == 'windows-latest'
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ matrix.os }}-stack
      - uses: mstksg/setup-stack@69e4283faeb7a89f26326daa36e9cc0fa7a023bd
      - name: Build
        run: stack build --fast
      - name: Run tests
        run: stack test --fast
